### ISSUE TITLE
Help Needed/Todo

### ISSUE THREAD

**Issue by xinitrc86** [xinitrc86/adash-services#1]
Greetings traveller,
If you came this far, perhaps you are interested in helping and doing one if the following?

- [ ]  Better error handling (Cli,Services)
- [ ]  Improve documentation (Cli,Services,Monitor)
- [ ]  Improve tests (Cli,Services,Monitor)
- [ ]  Downport Services to 740sp05 (first time ABAP CDS came out) (Services)
- [ ]  "Add Results" to allow monitoring of other sources tests together (Cli,Services)
- [ ]  "Add Package" for monitoring from the UI (Monitor)
- [ ]  "Total" tile for currently displaying results (Monitor)
- [ ]  "Last change" information hierarchly (Services on summarizing results,Monitor)
